name: lablebwallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^1.0.0
  feather_icons: ^1.2.0
  algorand_dart: ^1.0.3
  line_awesome_flutter: ^2.0.0
  barcode_image: ^2.0.1
  clipboard: ^0.1.3
  animator: ^3.1.0
  lottie: ^1.2.2
  get_storage: 2.0.3
  url_launcher: ^6.1.4
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

